ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS job_type VARCHAR(100);

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0;

ALTER TABLE jobs
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;